.TH SUBEXTRACT 1 2019\-02\-01 Linx "User Manuals"
.SH NAME
.PP
\fB\fCsubextract\fR \- Sync and extract packages for
Sublime Text

.SH SYNOPSIS
.PP
.RS

.nf
subextract [\-\-clean|\-c] [\-\-blank|\-d] [\-\-quite|\-q] [\-\-extract|\-e] [\-\-force|\-f] [\-\-sync|\-s PACKAGE\_DIRECTORY]
subextract \-\-help|\-h
subextract \-\-version|\-v

.fi
.RE

.SH DESCRIPTION
.PP
\fB\fCsubextract\fR can be used for one or more of the
following things:

.RS
.IP \(bu 2

.PP
bulk extract (\fB\fC\-\-extract\fR) setting and keymap files from installed packages, and move them to the User package, while blanking (\fB\fC\-\-blank\fR) (\fIoptional\fP) the default ones.
.IP \(bu 2

.PP
sync (\fB\fC\-\-sync\fR) the Package directory with a package directory outside your sublime directory (\fIfi the packages directory in this repo\fP)
.IP \(bu 2

.PP
move all currently installed packages (\fB\fC\-\-clean\fR) to a backup directory.

.RE

.SH OPTIONS
.PP
\fB\fC\-\-clean\fR|\fB\fC\-c\fR
.br
Move the current \fI$PKG\_DIR\fP to \fI$SUB\_DIR/backup\fP
before any other operations.

.PP
\fB\fC\-\-blank\fR|\fB\fC\-d\fR
.br
Blank extracted default files. (only in effect
when \fB\fC\-\-extract\fR is used)

.PP
\fB\fC\-\-quite\fR|\fB\fC\-q\fR
.br
Execute without output and messages.

.PP
\fB\fC\-\-extract\fR|\fB\fC\-e\fR
.br
Extract packages default settingfiles to
\fI$PKG\_DIR\fP

.PP
\fB\fC\-\-force\fR|\fB\fC\-f\fR
.br
Force files from PACKAGE\_DIRECTORY to overwrite,
no matter if target file exists (\fB\fC\-p\fR) or is newer
(\fB\fC\-s\fR).

.PP
\fB\fC\-\-sync\fR|\fB\fC\-s\fR PACKAGE\_DIRECTORY
.br
Sync files in \fIPACKAGE\_DIRECTORY\fP with files in
\fI$PKG\_DIR\fP\&. Works both ways, the newest file will
overwrite the oldest.

.PP
\fB\fC\-\-help\fR|\fB\fC\-h\fR
.br
Show help and exit.

.PP
\fB\fC\-\-version\fR|\fB\fC\-v\fR
.br
Show version and exit.

.SH ENVIRONMENT
.PP
\fB\fCSUBLIME\_DIR\fR
.br
sublimes config dir location. usually located at:
 \fB\fC\~/.config/sublime\-text\-3\fR defaults to:
$XDG\_CONFIG\_HOME/sublime\-text\-3

.SH FILES
.PP
$SUB\_DIR \- sublimes config directory.
.br
defaults to: \fI$HOME/.config/sublime\-text\-3\fP

.PP
$OPT\_DIR \- core package directory defaults to:
\fI/opt/sublime\_text/Packages\fP

.PP
$TMP\_DIR \- temporary directory where package
files get extracted to.
.br
defaults to: \fI/tmp/subextract\fP

.PP
$ZIP\_DIR \- installed (\fIpacked\fP) packages
directory.
.br
defaults to: \fI$SUB\_DIR/Installed Packages\fP

.PP
$PKG\_DIR \- (\fIunpacked\fP) packages directory.
.br
defaults to: \fI$SUB\_DIR/Packages\fP

.PP
$USR\_DIR \- User package directory.
.br
defaults to: \fI$PKG\_DIR/User\fP

.PP
$DOC\_DIR \- directory where readmes and wikis are
stored.
.br
defaults to: \fI$USR\_DIR/dox\fP

.PP
$DEF\_DIR \- directory where default config files
are backed up.
.br
defaults to: \fI$DOC\_DIR/defaults\fP

.PP
$USR\_DIR/projects/\fIsublime.sublime\-project\fP
.br
project file.

.SH DEPENDENCIES
.PP
\fB\fCbash\fR \fB\fCgawk\fR \fB\fCunzip\fR \fB\fCsublime\_text\fR

.PP
budRich 
\[la]https://github.com/budlabs\[ra]

.SH SEE ALSO
.PP
bash(1), awk(1), unzip(1),
