.TH BROWSERPREVIEW 1 2018\-08\-15 Linux "User Manuals"
.SH NAME
.PP
\fB\fCbrowserpreview\fR \- opens target url or file in vivaldi

.SH SYNOPSIS
.PP
\fB\fCbrowserpreview\fR [\fB\fC\-v\fR|\fB\fC\-h\fR]
.br
\fB\fCbrowserpreview\fR URL
.br
\fB\fCbrowserpreview\fR FILE

.SH DESCRIPTION
.PP
\fB\fCbrowserpreview\fR opens URL or FILE in vivaldi, and
places the vivaldi window in container D, hides, container
B set the AB split to 900 and focuses the main sublime window.

.PP
I created this to go with the sublime text package
\fB\fCMarkdownPreview\fR\&.

.SH OPTIONS
.PP
\fB\fC\-v|\-\-version\fR
.br
Show version and exit.

.PP
\fB\fC\-h|\-\-help\fR
.br
Show help and exit.

.SH DEPENDENCIES
.PP
go\-md2man
.br
Sublime Text
.br
Vivaldi
.br
i3fyra
.br
i3run

.SH AUTHOR
.PP
budRich 
\[la]robstenklippa@gmail.com\[ra]

\[la]https://budrich.github.io\[ra]

.SH SEE ALSO
.PP
wmctrl(1)
