.TH SUBDOX 1 2018\-08\-05 Linux "User Manuals"
.SH NAME
.PP
\fB\fCsubdox\fR \- Downloads sublime related documentation.

.SH SYNOPSIS
.PP
\fB\fCsubextract\fR [\fB\fC\-v\fR|\fB\fC\-h\fR]

.SH DESCRIPTION
.PP
\fB\fCsubdox\fR uses \fB\fCGTFM\fR to download sublime related
documentation. See \fB\fCsubdox.ini\fR for more info.

.SH DOCUMENTATION
.PP
The following documentation is downloaded with \fB\fCsubdox\fR:

.RS
.IP \(bu 2
SublimeLinter
.br
.IP \(bu 2
Sublime official
.br
.IP \(bu 2
Sublime unofficial
.br
.IP \(bu 2
Package Control
.br

.RE

.SH OPTIONS
.PP
\fB\fC\-v\fR
.br
Show version and exit.

.PP
\fB\fC\-h\fR
.br
Show help and exit.

.SH DEPENDENCIES
.PP
GTFM

.SH AUTHOR
.PP
budRich 
\[la]robstenklippa@gmail.com\[ra]

\[la]https://budrich.github.io\[ra]

.SH SEE ALSO
.PP
GTFM(1)
