#!/usr/bin/env bash

# delete files only used to build:
# program.sh and init.sh

projectdir=$1
rm -f "$projectdir"/___{version,envs,help,getopt}

projectname="${projectdir##*/}"
repodir="$(git rev-parse --show-toplevel)"
mv -f "$projectdir"/program.sh "$repodir/scripts/$projectname"

if [[ -d "$projectdir/wiki" ]]; then
  # create TOC for wiki
  wroot="$projectdir/wiki"
  wdir="$wroot/doc"
  wurl="https://github.com/budlabs/${projectname}/wiki"

  l1=l2=l3=""
  # if last main != new main
  for f in "$wdir/"*.md; do
    fn="${f#${wdir}/}"
    loc="${fn%%_*}"
    name="${fn%.*}"
    name="${name#*_}"
    md="[$name]($wurl/${loc}_${name})"
    s1="${loc:0:2}"
    s2="${loc:2:1}"
    if [[ $l1 != "$s1" ]]; then
      echo "- $md"
    elif [[ $l2 != "$s2" ]]; then
      echo "  - $md"
    else
      echo "    - $md"
    fi
    l1="$s1"
    l2="$s2"
  done > "$wroot/_Sidebar.md"
fi
