.TH SUBLAUNCH 1 2019\-01\-17 Linx "User Manuals"
.SH NAME
.PP
\fB\fCsublaunch\fR \- Run or raise sublime with a
specific profile and file

.SH SYNOPSIS
.PP
.RS

.nf
sublaunch [\-\-instance|\-i INSTANCE] [\-\-options|\-o  OPTIONS] [\-\-project|\-j  PROJECT] [FILE]
sublaunch [\-\-class|\-c    CLASS] [\-\-options|\-o  OPTIONS] [\-\-project|\-j  PROJECT] [FILE]
sublaunch [\-\-profile|\-p  PROFILE] [\-\-options|\-o  OPTIONS] [\-\-project|\-j  PROJECT] [FILE]
sublaunch \-\-help|\-h
sublaunch \-\-version|\-v

.fi
.RE

.SH DESCRIPTION
.PP
\fB\fCsublaunch\fR takes a number of criterion to
identify a sublime window. If \fB\fCsublaunch\fR can'
find a open window matching the criteria. A new
sublime window will be opened and it's \fBinstance
name\fP will be renamed to match the criteria.

.SH OPTIONS
.PP
\fB\fC\-\-instance\fR|\fB\fC\-i\fR INSTANCE
.br
Set the criterion to be a window with the class
name CLASS. Defaults to the value of
SUBLIME\_TITS\_SRCH.

.PP
\fB\fC\-\-options\fR|\fB\fC\-o\fR OPTIONS

.PP
\fB\fC\-\-project\fR|\fB\fC\-j\fR PROJECT
.br
If a project in $PROJECT\_DIR with the name
PROJECT.sublime\-project exist. That project will
get opened if the window doesn't exist. If both
this and \fB\fC\-\-profile\fR is set, \fB\fC\-\-profile\fR will have
priority.

.PP
\fB\fC\-\-class\fR|\fB\fC\-c\fR CLASS

.PP
\fB\fC\-\-profile\fR|\fB\fC\-p\fR PROFILE
.br
Set the criterion to be a window with the
instance name: \fB\fCsublime\_PROFILE\fR\&. And if a project
in $PROJECT\_DIR with the name
PROFILE.sublime\-project exist. That project will
get opened if the window doesn't exist.

.PP
\fB\fC\-\-help\fR|\fB\fC\-h\fR
.br
Show help and exit.

.PP
\fB\fC\-\-version\fR|\fB\fC\-v\fR
.br
Show version and exit

.SH ENVIRONMENT
.PP
\fB\fCSUBLIME\_TITS\_CRIT\fR
.br
Default criteria to use if \fB\fC\-\-class\fR or
\fB\fC\-\-instance\fR is not set. defaults to: class

.PP
\fB\fCSUBLIME\_TITS\_SRCH\fR
.br
Default search string to use if \fB\fC\-\-class\fR or
\fB\fC\-\-instance\fR is not set. defaults to: Sublime\_text

.PP
\fB\fCSUBLIME\_PROJECTS\_DIR\fR
.br
Directory where sublime project files are
located. defaults to:
$XDG\_CONFIG\_HOME/sublime\-text\-3/Packages/User/Projects

.SH DEPENDENCIES
.PP
\fB\fCbash\fR \fB\fCxdotool\fR \fB\fCsublime\_text\fR

.PP
budRich 
\[la]https://github.com/budlabs\[ra]

.SH SEE ALSO
.PP
bash(1), xdotool(1),
